# Generated by Django 5.1.6 on 2025-04-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
        ('users', '0004_guestuser'),
    ]

    operations = [
    ]
