# Generated by Django 5.1.6 on 2025-04-11 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0027_remove_resume_guest_user_resumedownloadlog_and_more'),
        ('users', '0005_merge_0004_alter_user_email_0004_guestuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestUser',
        ),
    ]
