# Generated by Django 5.1.6 on 2025-02-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='privacy_settings',
            new_name='privacy_setting',
        ),
    ]
