# Generated by Django 5.1.6 on 2025-03-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0012_alter_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='currently_working',
            field=models.BooleanField(default=False),
        ),
    ]
