# Generated by Django 5.1.6 on 2025-03-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0013_workexperience_currently_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
