# Generated by Django 5.1.6 on 2025-03-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0014_skill_proficiency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-created_at']},
        ),
    ]
