# Generated by Django 5.1.6 on 2025-03-10 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0016_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to='resumes.resume'),
        ),
    ]
