# Generated by Django 5.1.6 on 2025-03-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0017_alter_personaldetails_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personal_details', serialize=False, to='resumes.resume'),
        ),
    ]
