# Generated by Django 5.1.6 on 2025-03-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0022_education_currently_studying'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
