# Generated by Django 5.1.6 on 2025-04-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0024_alter_resume_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_anonymized',
            field=models.BooleanField(default=False),
        ),
    ]
