# Generated by Django 5.1.6 on 2025-02-25 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_remove_workexperience_currently_working_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='github',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='linkedin',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
