# Generated by Django 5.1.6 on 2025-02-25 11:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_alter_personaldetails_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to='resumes.resume'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
