# Generated by Django 5.1.6 on 2025-03-10 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0018_remove_personaldetails_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personal_details', serialize=False, to='resumes.resume'),
        ),
    ]
