# Generated by Django 5.1.6 on 2025-03-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0019_alter_personaldetails_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='resumes.resume')),
            ],
        ),
    ]
