# Generated by Django 5.1.6 on 2025-03-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0021_auto_20250314_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='currently_studying',
            field=models.BooleanField(default=False),
        ),
    ]
