# Generated by Django 5.1.6 on 2025-04-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0023_resume_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(default='template_classic', max_length=50),
        ),
    ]
