# Generated by Django 5.1.6 on 2025-04-16 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0027_remove_resume_guest_user_resumedownloadlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeviewlog',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='resumeviewlog',
            name='user',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resumes.resume')),
            ],
        ),
        migrations.DeleteModel(
            name='ResumeDownloadLog',
        ),
        migrations.DeleteModel(
            name='ResumeViewLog',
        ),
    ]
